// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLevRc0SipuN5C7tXCT3cKPnaz5qYx-A4',
    appId: '1:48698513670:web:31a014090469b3411fa687',
    messagingSenderId: '48698513670',
    projectId: 'watcherapp-f9a63',
    authDomain: 'watcherapp-f9a63.firebaseapp.com',
    storageBucket: 'watcherapp-f9a63.appspot.com',
    measurementId: 'G-X6YVS9CBMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAFCV8mju3oE0XmBTu-aq3nkQUMg542AI',
    appId: '1:48698513670:android:09c7d13f937ac0511fa687',
    messagingSenderId: '48698513670',
    projectId: 'watcherapp-f9a63',
    storageBucket: 'watcherapp-f9a63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa1HEnTdRBUy8s_8JNM3a17wt5EG62SbY',
    appId: '1:48698513670:ios:338fdb438bf504c51fa687',
    messagingSenderId: '48698513670',
    projectId: 'watcherapp-f9a63',
    storageBucket: 'watcherapp-f9a63.appspot.com',
    iosClientId: '48698513670-jcunc9qm1l89kg3dajfu75qvdl90uvq8.apps.googleusercontent.com',
    iosBundleId: 'com.iot.watcherApp',
  );
}
